server:
  port : 8866
  tomcat:
    max-threads: 500
    max-http-header-size: 8192  
  
spring:
  application:
    name: eprescription
  datasource:
    name: hpk
    url: jdbc:mysql://127.0.0.1:3306/kph?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useUnicode=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 50
    initialSize: 10
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  datasource2:
    name: jxfy
    url: jdbc:mysql://127.0.0.1:3306/jxfy?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useUnicode=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 50
    initialSize: 10
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#mybatis
mybatis:
  typeAliasesPackage: com.yyg.eprescription.entity
  mapperLocations: classpath:mapper/*.xml
  jxfyTypeAliasesPackage: com.yyg.eprescription.jxfy.entity
  jxfyMapperLocations: classpath:jxfymapper/*.xml
 
#log
logging:
  path:
    name: ./logs
  level:
    root: INFO
    
#医院系统配置
pay:
  host: http://127.0.0.1:8867
